import { Content } from './types'

const now = new Date()
const daysAgo = (d: number): string =>
  new Date(now.getTime() - d * 86400000).toISOString().split('T')[0]

export const TEST_CONTENTS: Content[] = [
  {
    id: 'test-1',
    user_id: 'test-user',
    title: 'Elden Ring',
    type: 'game',
    price: 8800,
    purchased_at: daysAgo(487),
    release_date: daysAgo(520),
    platform: 'PS5',
    cover_image_url: null,
    status: 'unplayed',
    tags: ['RPG', 'フロム'],
    freshness_source: 'manual',
    created_at: daysAgo(487),
    updated_at: daysAgo(487),
  },
  {
    id: 'test-2',
    user_id: 'test-user',
    title: '三体',
    type: 'book',
    price: 2200,
    purchased_at: daysAgo(312),
    release_date: daysAgo(400),
    platform: null,
    cover_image_url: null,
    status: 'unplayed',
    tags: ['SF', '中国'],
    freshness_source: 'manual',
    created_at: daysAgo(312),
    updated_at: daysAgo(312),
  },
  {
    id: 'test-3',
    user_id: 'test-user',
    title: 'FF7 リバース',
    type: 'game',
    price: 9878,
    purchased_at: daysAgo(203),
    release_date: daysAgo(210),
    platform: 'PS5',
    cover_image_url: null,
    status: 'in_progress',
    tags: ['RPG', 'スクエニ'],
    freshness_source: 'manual',
    created_at: daysAgo(203),
    updated_at: daysAgo(50),
  },
  {
    id: 'test-4',
    user_id: 'test-user',
    title: 'オッペンハイマー',
    type: 'movie',
    price: 2400,
    purchased_at: daysAgo(120),
    release_date: daysAgo(300),
    platform: 'Blu-ray',
    cover_image_url: null,
    status: 'unplayed',
    tags: ['洋画', '伝記'],
    freshness_source: 'manual',
    created_at: daysAgo(120),
    updated_at: daysAgo(120),
  },
  {
    id: 'test-5',
    user_id: 'test-user',
    title: 'チェンソーマン 1〜10巻セット',
    type: 'manga',
    price: 5500,
    purchased_at: daysAgo(89),
    release_date: daysAgo(600),
    platform: null,
    cover_image_url: null,
    status: 'unplayed',
    tags: ['少年漫画', 'ジャンプ'],
    freshness_source: 'manual',
    created_at: daysAgo(89),
    updated_at: daysAgo(89),
  },
  {
    id: 'test-6',
    user_id: 'test-user',
    title: '推しの子',
    type: 'anime',
    price: 0,
    purchased_at: daysAgo(400),
    release_date: daysAgo(420),
    platform: 'Amazon Prime',
    cover_image_url: null,
    status: 'unplayed',
    tags: ['アニメ', '芸能'],
    freshness_source: 'manual',
    created_at: daysAgo(400),
    updated_at: daysAgo(400),
  },
  {
    id: 'test-7',
    user_id: 'test-user',
    title: 'Hades II',
    type: 'game',
    price: 3200,
    purchased_at: daysAgo(45),
    release_date: daysAgo(50),
    platform: 'Steam',
    cover_image_url: null,
    status: 'unplayed',
    tags: ['ローグライク', 'インディー'],
    freshness_source: 'manual',
    created_at: daysAgo(45),
    updated_at: daysAgo(45),
  },
  {
    id: 'test-8',
    user_id: 'test-user',
    title: 'ファスト&スロー（上下巻）',
    type: 'book',
    price: 3300,
    purchased_at: daysAgo(730),
    release_date: daysAgo(2000),
    platform: null,
    cover_image_url: null,
    status: 'unplayed',
    tags: ['ビジネス', '心理学'],
    freshness_source: 'manual',
    created_at: daysAgo(730),
    updated_at: daysAgo(730),
  },
]

export const TEST_USER_ID = 'test-user'
